name: M3D
favicon: null
layout_spectrum: 0.91074
typography_spectrum: 0.9734212700277567
title: Mike 3 D
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.7936959275975823
  saturation: 0.9268188367132097
  rhythmicContrast: 0.6047782660461962
purpose: []
